services:
  redis:
    image: redis:latest
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - wishlist-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mymongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mymongopassword
    volumes:
      - mongo-data:/data/db
      - mongo-config-data:/data/configdb
    networks:
      - wishlist-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://mymongoadmin:mymongopassword@mongodb:27017/?authSource=admin"
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - wishlist-net

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-wishlist-container
    restart: on-failure
    depends_on:
      - mongodb
      - mongo-express
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.docker
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules
    command: pnpm run start:dev:ts
    networks:
      - wishlist-net

volumes:
  api_node_modules:
  mongo-data:
  mongo-config-data:

networks:
  wishlist-net:
    driver: bridge