FROM node:22-alpine
WORKDIR /usr/src/app

# 1) Instala pnpm e dependências
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm@10.11.0 \
  && pnpm install

# 2) Copia configs TypeScript (necessário para ts-node-dev)
COPY tsconfig*.json ./

# 3) Porta e comando default
EXPOSE 3000
CMD ["pnpm", "run", "start:dev:ts"]
